load("~/Money/Money.txt")
View(Money)
FILE <- "~/Money/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
summary (dat)
v <- c("M2", "interest", "GDP", "Year")
print (v)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
lm (formula = M2 ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat, TRUE)
summary(m)
//parameter estimates//
coef(m)
anova.lm(m)
anova(m)
coefficients(m)
fitted(m)
residuals(m)
anova.glm(m)
summary(m)
anova.glm
deviance(m)
anova.glm(m)
anova.lmlist(m)
