View(Money)
setwd("~/Money")
View(Money)
View(Money)
Money <- read.delim("~/Dropbox/Metrics Data Files/Money.txt")
View(Money)
View(Money)
FILE <- "~/Dropbox/Metrics Data Files/Money.txt"
setwd("~/Money")
FILE <- "~/Dropbox/Metrics Data Files/Money.txt"
setwd("~/Money")
Money <- read.delim("~/Money/Money.txt")
View(Money)
View(Money)
View(Money)
load("~/Money/Money.txt")
View(Money)
FILE <- "~/Money/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
summary (dat)
v <- c("M2", "interest", "GDP", "Year")
print (v)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
lm (formula = M2 ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat, TRUE)
summary(m)
//parameter estimates//
  coef(m)
anova.lm(m)
anova(m)
coefficients(m)
fitted(m)
residuals(m)
summary(m)
deviance(m)
anova.lmlist(m)
load("~/Money/Money.txt")
View(Money)
FILE <- "~/Money/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
summary (dat)
v <- c("M2", "interest", "GDP", "Year")
print (v)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
lm (formula = M2 ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat, TRUE)
summary(m)
//parameter estimates//
  coef(m)
anova.lm(m)
anova(m)
coefficients(m)
residuals(m)
summary(m)
deviance(m)
anova.lmlist(m)
load("~/Money/Money.txt")
View(Money)
FILE <- "~/Money/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
summary (dat)
v <- c("M2", "interest", "GDP", "Year")
print (v)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
lm (formula = M2 ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat, TRUE)
summary(m)
FILE <- "~/Dropbox/Metrics Data Files/Money.txt"
dat <_ read.table(file = FILE, header = TRUE)
dat <- read.table(file = FILE, header = TRUE)
summary(dat)
v <- c("M2", "interest", "GDP", "Year")
print(v)
summary(dat)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
summary(dat)
lm(formula = M2 ~ interest + GDP, data=dat)
lm(formula = M2*f ~ interest + GDP, data=dat)
lm(formula = M2(f) ~ interest + GDP, data=dat)
lm(formula = M2$f ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat)
summary(m)
anova(m)
plot (m)
?plot
xlab("Years")
?ggplot
??ggplot
FILE <- "~/Dropbox/Metrics Data Files/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
v <- c("M2", "interest", "GDP", "Year")
autoplot(m)
autoplot(Year, M2, GDP)
ggplot(Year, M2, GDP)
library("AER", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("boot", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
ggplot(Year, M2, GDP)
library("dynlm", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
ggplot(Year, M2, GDP)
library("ggplot2", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
ggplot(Year, M2, GDP)
ggplot(M2, GDP)
ggplot("M2", "GDP")
aes_string <- ggplot("M2", "GDP")
ggplot(m)
library("evaluate", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("Formula", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("grid", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("labeling", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("manipulate", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("multcomp", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("nlme", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("plyr", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("rstudio", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("scales", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("SparseM", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
detach("package:survival", unload=TRUE)
ggplot(m)
ggplot(m, M2)
?ggplot
ggplot(2, aes(x, y, "Years"))
ggplot(df, aes(x, y, "Years"))
ggplot(df, aes(x, y))
ggplot(df, aes(m, f))
ggplot(aes(m, f))
ggplot(df)
ggplot(dat)
ggplot(dat, m)
ggplot(dat, aes(m))
ggplot(dat, aes(m, f))
ggplot(dat, aes(x = Years, y = m))
ggplot(data=dat, aes(x = Years, y = m))
ggplot(df, aes(x = Years, y = m))
?plot
install.packages("ggplot2")
install.packages("ggplot2")
install.packages("gcookbook")
library(ggplot2)
library(gcookbook)
plot(v, f, type="l")
View(Money)
setwd("~/Money")
View(Money)
View(Money)
Money <- read.delim("~/Dropbox/Metrics Data Files/Money.txt")
View(Money)
View(Money)
FILE <- "~/Dropbox/Metrics Data Files/Money.txt"
setwd("~/Money")
FILE <- "~/Dropbox/Metrics Data Files/Money.txt"
setwd("~/Money")
Money <- read.delim("~/Money/Money.txt")
View(Money)
View(Money)
View(Money)
load("~/Money/Money.txt")
View(Money)
FILE <- "~/Money/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
summary (dat)
v <- c("M2", "interest", "GDP", "Year")
print (v)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
lm (formula = M2 ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat, TRUE)
summary(m)
//parameter estimates//
  coef(m)
anova.lm(m)
anova(m)
coefficients(m)
fitted(m)
residuals(m)
summary(m)
deviance(m)
anova.lmlist(m)
load("~/Money/Money.txt")
View(Money)
FILE <- "~/Money/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
summary (dat)
v <- c("M2", "interest", "GDP", "Year")
print (v)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
lm (formula = M2 ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat, TRUE)
summary(m)
//parameter estimates//
  coef(m)
anova.lm(m)
anova(m)
coefficients(m)
residuals(m)
summary(m)
deviance(m)
anova.lmlist(m)
load("~/Money/Money.txt")
View(Money)
FILE <- "~/Money/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
summary (dat)
v <- c("M2", "interest", "GDP", "Year")
print (v)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
lm (formula = M2 ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat)
summary(m)
FILE <- "~/Dropbox/Metrics Data Files/Money.txt"
dat <_ read.table(file = FILE, header = TRUE)
dat <- read.table(file = FILE, header = TRUE)
summary(dat)
v <- c("M2", "interest", "GDP", "Year")
print(v)
summary(dat)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
summary(dat)
lm(formula = M2 ~ interest + GDP, data=dat)
lm(formula = M2*f ~ interest + GDP, data=dat)
lm(formula = M2(f) ~ interest + GDP, data=dat)
lm(formula = M2$f ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat)
print(m)
summary(m)
anova(m)
confint(m)
##covariance of estimates##
vcov(m)
coef(m)
effects(m)
deviance(m)
m <- aov(v ~ f)
