load("~/Money/Money.txt")
View(Money)
FILE <- "~/Money/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
summary(dat)
v <- c("M2", "interest", "GDP", "Year")
print(v)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
summary(dat)
lm(formula = M2 ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat)
print(m)
summary(m)
anova(m)
confint(m)
