View(Money)
setwd("~/Money")
View(Money)
View(Money)
Money <- read.delim("~/Dropbox/Metrics Data Files/Money.txt")
View(Money)
View(Money)
FILE <- "~/Dropbox/Metrics Data Files/Money.txt"
setwd("~/Money")
FILE <- "~/Dropbox/Metrics Data Files/Money.txt"
setwd("~/Money")
Money <- read.delim("~/Money/Money.txt")
View(Money)
View(Money)
View(Money)
load("~/Money/Money.txt")
View(Money)
FILE <- "~/Money/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
summary (dat)
v <- c("M2", "interest", "GDP", "Year")
print (v)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
lm (formula = M2 ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat, TRUE)
summary(m)
//parameter estimates//
  coef(m)
anova.lm(m)
anova(m)
coefficients(m)
fitted(m)
residuals(m)
summary(m)
deviance(m)
anova.lmlist(m)
load("~/Money/Money.txt")
View(Money)
FILE <- "~/Money/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
summary (dat)
v <- c("M2", "interest", "GDP", "Year")
print (v)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
lm (formula = M2 ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat, TRUE)
summary(m)
//parameter estimates//
  coef(m)
anova.lm(m)
anova(m)
coefficients(m)
residuals(m)
summary(m)
deviance(m)
anova.lmlist(m)
load("~/Money/Money.txt")
View(Money)
FILE <- "~/Money/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
summary (dat)
v <- c("M2", "interest", "GDP", "Year")
print (v)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
lm (formula = M2 ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat, TRUE)
summary(m)
FILE <- "~/Dropbox/Metrics Data Files/Money.txt"
dat <_ read.table(file = FILE, header = TRUE)
dat <- read.table(file = FILE, header = TRUE)
summary(dat)
v <- c("M2", "interest", "GDP", "Year")
print(v)
summary(dat)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
summary(dat)
lm(formula = M2 ~ interest + GDP, data=dat)
lm(formula = M2*f ~ interest + GDP, data=dat)
lm(formula = M2(f) ~ interest + GDP, data=dat)
lm(formula = M2$f ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat)
summary(m)
anova(m)
plot (m)
?plot
xlab("Years")
?ggplot
??ggplot
FILE <- "~/Dropbox/Metrics Data Files/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
v <- c("M2", "interest", "GDP", "Year")
autoplot(m)
autoplot(Year, M2, GDP)
ggplot(Year, M2, GDP)
library("AER", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("boot", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
ggplot(Year, M2, GDP)
library("dynlm", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
ggplot(Year, M2, GDP)
library("ggplot2", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
ggplot(Year, M2, GDP)
ggplot(M2, GDP)
ggplot("M2", "GDP")
aes_string <- ggplot("M2", "GDP")
ggplot(m)
library("evaluate", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("Formula", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("grid", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("labeling", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("manipulate", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("multcomp", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("nlme", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("plyr", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("rstudio", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("scales", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
library("SparseM", lib.loc="/Library/Frameworks/R.framework/Versions/3.0/Resources/library")
detach("package:survival", unload=TRUE)
ggplot(m)
ggplot(m, M2)
?ggplot
ggplot(2, aes(x, y, "Years"))
ggplot(df, aes(x, y, "Years"))
ggplot(df, aes(x, y))
ggplot(df, aes(m, f))
ggplot(aes(m, f))
ggplot(df)
ggplot(dat)
ggplot(dat, m)
ggplot(dat, aes(m))
ggplot(dat, aes(m, f))
ggplot(dat, aes(x = Years, y = m))
ggplot(data=dat, aes(x = Years, y = m))
ggplot(df, aes(x = Years, y = m))
?plot
install.packages("ggplot2")
install.packages("ggplot2")
install.packages("gcookbook")
library(ggplot2)
library(gcookbook)
plot(v, f, type="l")
View(Money)
setwd("~/Money")
View(Money)
View(Money)
Money <- read.delim("~/Dropbox/Metrics Data Files/Money.txt")
View(Money)
View(Money)
FILE <- "~/Dropbox/Metrics Data Files/Money.txt"
setwd("~/Money")
FILE <- "~/Dropbox/Metrics Data Files/Money.txt"
setwd("~/Money")
Money <- read.delim("~/Money/Money.txt")
View(Money)
View(Money)
View(Money)
load("~/Money/Money.txt")
View(Money)
FILE <- "~/Money/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
summary (dat)
v <- c("M2", "interest", "GDP", "Year")
print (v)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
lm (formula = M2 ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat, TRUE)
summary(m)
//parameter estimates//
  coef(m)
anova.lm(m)
anova(m)
coefficients(m)
fitted(m)
residuals(m)
summary(m)
deviance(m)
anova.lmlist(m)
load("~/Money/Money.txt")
View(Money)
FILE <- "~/Money/Money.txt"
dat <- read.table(file = FILE, header = TRUE)
summary (dat)
v <- c("M2", "interest", "GDP", "Year")
print (v)
f <- c("Year$M2", "Year$interest", "Year$GDP")
print(f)
lm (formula = M2 ~ interest + GDP, data=dat)
m <- lm(formula = M2 ~ interest + GDP, data=dat, TRUE)
summary(m)
//parameter estimates//
  coef(m)
anova.lm(m)
anova(m)
coefficients(m)
residuals(m)
summary(m)
deviance(m)
anova.lmlist(m)

confint(m)
##covariance of estimates##
vcov(m)
coef(m)
effects(m)
deviance(m)
m <- aov(v ~ f)
slope <- coef(m)
slope
print(slope)
plot(slope)
mode(m)
df.residual(m)
coefficients(m)
residuals(m)
effects(m)
rank(m)
fitted.values(m)
xlevels(m)
model(m)
coeftest(m)
confint(m)
fit <- lm(M2 ~ interest + GDP, data=dat)
summary(fit)
xlab="Years"
logit(m)
fit <- glm(M2 ~ interest + GDP, data=mydat, family=binomial(m))
print(fit)
summary(fit)
exp(confint(fit))
exp(coef(fit))
predict(fit, type="response")
residuals(fit, type="deviance")
anova(fit1,fit2, test="Chisq")
log(fit)
log(m)
loglm <- c(formula= log("M2") ~ log("interest") + log("GDP"))
summary(loglm)
x1 <- "interest"
x2 <- "GDP"
y <- "M2"
log(x1, base = exp(1))

log(x1)
log(interest)

lm(formula = log(M2) ~ log(interest) + log(GDP), data = dat)
s <- lm(formula = log(M2) ~ log(interest) + log(GDP), data=dat)
anova(s)
coefficients(s)
summary(s)
coef(s)
vcov(s)
##Difference##
FILE <- "~/Dropbox/Metrics Data Files/PS4diff.txt"
dat2 <- read.table(file = FILE, header = TRUE)
summary(dat2)
v <- c("dM2t", "dInt", "dGDP", "Year")
print (v)
f <- c("Year$dM2t", "Year$dInt", "Year$dGDP")
print(f)
lm (formula = dM2t ~ dInt + dGDP, data=dat2)
n <- lm(formula = dM2t ~ dInt + dGDP, data=dat2, TRUE)
print(n)
summary(n)
confint(n)
coef(n)
vcov(n)
anova(n)
##log difference model##
loglm(formula = dM2t ~ dInt + dGDP, data=dat2)
q <- loglm(formula = dM2t ~ dInt + dGDP, data=dat2)
summary(q)
coef(q)
anova(q)
resid(q)
deviance(q)
effects(q)
dat2$Year <- factor(dat2$Year)
glm(formula = dM2t ~ dInt + dGDP, data = dat2)
coef(log)